FROM bitnami/spark:3.5

# Download and install the Kafka connector JAR file
RUN curl -L https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.0.0/spark-sql-kafka-0-10_2.12-3.0.0.jar -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.0.0.jar